name: citros-citros
description: run simulations and generate reports.
author: lulav-citros

branding:
  icon: 'activity'
  color: 'green'

# Define your inputs here.
inputs:
  name:
    description: Batch name
    required: true
    default: citros-action
  message:
    description: Batch message
    required: true
    default: 'batch run from github'
  completions:
    description: How many times to run the simulation
    required: true
    default: 1
  simulation:
    description: The name of the simulation to run
    required: true

# Define your outputs here.
outputs:
  time:
    description: The time we greeted you

runs:
  using: node20
  main: dist/index.js
